---
title: "GEOL 7132 HW 3"
author: "Allison Noble"
date: "2025-04-24"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(mosaic)
library(ggplot2)
```



### Variables
```{r}
h<- c(10, 20, 30, 40, 50)
Hd<- 2
t<- 10
Cd<- .003
Ric<- 0.25
s<- 1.6
rhos<- 2600
omega<- (2*pi)/t
g<- 9.81

Qr<- c(3, 1)
```

### 1)
```{r}
wavelengths<- data.frame(h = h, L = 0)
temp<- vector(length = 5)

for (i in 1:length(h)) {
  temp<- findZeros((((t^2)/(2*pi))*g*tanh((2*wavelengths$h[i]*pi)/L)) - L ~ L, 
                   i = i, 
                   t = t, 
                   g = 9.81)
  wavelengths$L[i]<- temp[3,]
}

wavelengths
```


### 2)
```{r}
H<- c(2, 1.83, 1.83, 1.87, 1.91)
k<- (2*pi)/wavelengths$L

alphas<- data.frame(alpha1 = rep(0, times  = 5), alpha2 = rep(0, times = length(h)))

for (k in 1:length(Qr)){
  for (i in 1: length(h)){
    temp<- findZeros((8*((omega*H[i])^-3)*((sinh(k[i]*h[i]))^3)*Qr[i]*s*g*Cd*(Ric^-2)*(1/rhos)) - (a*((1 - ((a*Ric*(1/Cd))^2))^-1.5)) ~ a, i = i, k = k, near = 0.0013, within = .0012, npts = 10000)
    alphas[i,k]<- temp[1,]
  }
}  

8*((omega*H[1])^-3)*((sinh(k[1]*h[1]))^3)*Qr[1]*s*g*Cd*(Ric^-2)*(1/rhos)
#omega = omega, H = H[1], k = k[1], h = h[1], Qr = Qr[1], s = s, g = g, rhos = rhos
a<- .00135858285
(a*((1 - ((a*Ric*(1/Cd))^2))^-1.5)) - (8*((omega*H[1])^-3)*((sinh(k[1]*h[1]))^3)*Qr[1]*s*g*Cd*(Ric^-2)*(1/rhos))

fw2004 <- function(a) {
  (8*((omega*H[1])^-3)*((sinh(k[1]*h[1]))^3)*Qr[1]*s*g*Cd*(Ric^-2)*(1/rhos)) - (a*((1 - ((a*Ric*(1/Cd))^2))^-1.5))
}

ggplot() +
  stat_function(fun = fw2004) +
  geom_hline(yintercept = 0, color = "blue") +
  ylim(-0.02, 0.02) +
  xlim(0, 0.0025) +
  theme_classic()


findZeros((8*((omega*H[1])^-3)*((sinh(k[1]*h[1]))^3)*Qr[1]*s*g*Cd*(Ric^-2)*(1/rhos)) - (a*((1 - ((a*Ric*(1/Cd))^2))^-1.5)) ~ a, near = 0.0013, within = .0012, npts = 100000)
```

